networks:
  lrvlconsole_network:
    external: true

name: laravel-console-docker

services:
  app:
    image: nginx:latest
    container_name: exmpl-task-app
    ports:
      - "8813:80"
    volumes:
      - ./:/var/www/html
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - lrvlconsole_network
    restart: "no"

  php:
    build:
      context: .
      dockerfile: ./Docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
    expose:
      - "9000"
    networks:
      - lrvlconsole_network
    restart: "no"

  postgres:
    container_name: exmpl-task-pg_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5442:5432"
    networks:
      - lrvlconsole_network
    restart: "no"

volumes:
  postgres:
    driver: local
